name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7
      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Build project
        run: ./gradlew assembleDebug
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
      - name: cleanup keystore
        run: ./signing/cleanup.sh
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.7
        with:
          cmd: ./gradlew cAT
          api: 28
          tag: default
          abi: x86
      - name: Archive Espresso results
        uses: actions/upload-artifact@v2
        with:
          name: LiveEdgeDetection-Espresso-report
          path: app/build/reports/androidTests/connected
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: LiveEdgeDetection-logcat
          path: artifacts/logcat.log
      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        with:
          name: LiveEdgeDetection-Screenshots
          path: screenshots/adb
  Check:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: LiveEdgeDetection-Lint-report
          path: app/build/reports/lint-results.html
